### ISSUE TITLE
Incomplete or outdated API usage documentation?

### ISSUE THREAD

**Issue by woolwood** [lakhanmankani/metric-time#2]
I realise this was likely a one-off project so sorry to bug, but I just found this and wanted to try it out.

From the README:

```
>>> import metric_time
>>> metric_time.DecimalTime.now()
(8, 2, 88, 543) # Time in format (hours, minutes, seconds, milliseconds)
>>> metric_time.DecimalTime.decimal_time(datetime.datetime(year=2018, month=6, day=28, hour=13, minute=50, second=30))
(5, 76, 73, 611) # Time in format (hours, minutes, seconds, milliseconds)
>>> metric_time.RepublicanCalendar().now()
(226.91780821917808, 'Messidor', 10, 'Décadi') # Date in format (year, month, date, day)
>>> metric_time.RepublicanCalendar().republican_date(datetime.datetime(year=2020, month=5, day=20, tzinfo=pytz.reference.LocalTimezone()))
(228.81095890410958, 'Prairial', 2, 'Duodi') # Date in format (year, month, date, day)
```

However, these examples error out on type errors and name errors:
```
Python 3.8.9 (default, Apr 28 2021, 17:38:18) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import metric_time
>>> metric_time.DecimalTime.now()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: now() missing 1 required positional argument: 'self'
>>> metric_time.RepublicanCalendar().republican_date(datetime.datetime(year=2020, month=5, day=20, tzinfo=pytz.reference.LocalTimezone()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'datetime' is not defined
```

**Comment by lakhanmankani** [comment]
Hey, thanks for checking out the project. I've pushed a fix and updated the documentation. Let me know if that resolves your issue.

**Comment by woolwood** [comment]
Yes, thank you.

**Comment by lakhanmankani** [comment]
I'll go ahead and close this issue then.
